# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RiVyFQxoF2_9NY2z_fTC4Ss3As7Tnh8a
"""

#Apriori Algorithm in Python-Market Basket Analysis

#Problem Statement: The manager of a retail store is trying to find out an association rule between six items,
#to figure out which items are more often bought together so that he can keep the items together in order to increase sales.

#before we move forward we need to install 'apyori' package first
!pip install apyori

#import required Libraries
import numpy as np
import pandas as pd
from apyori import apriori

#Load the dataset
store_data=pd.read_csv('/content/Day1.csv', header=None)

#have a look at the dataset
print(store_data)

#find the shape of the dataset
store_data.shape

records = []
for i in range(0,22):
    records.append([str(store_data.values[i,j]) for j in range(0,6)])

records

#Building the first apriori model
association_rules = apriori(records, min_support = 0.50, min_confidence = 0.7, min_lift = 1.2, min_length = 2)
association_results =  list(association_rules)

#print the number of rules
print(len(association_results))

#have a glance at the rule
print(association_results)

#The support value for the first rule is 0.5. This number is calculated by dividing the number of transactions containing 'Milk', 'Bread' , and 'Butter' by the total number of transactions.

#The confidence level for the rule is 0.846, which shows that out of all the transactions that contain both 'Milk' and 'Bread', 84.6% contain 'butter' too.

#The lift of 1.241 tells us tha 'butter' is 1.241 times more likely to be bought by the customers who buy both 'milk' and 'butter' compared to the default likeihood sale of 'butter'.