# -*- coding: utf-8 -*-
"""asita_ganatra_dwm_practical_8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uhu0HPNHAHQZuUsQckH0HkQ_6bliG3Ud
"""

import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

#importing the dataset
dataset = pd.read_csv("/content/User_Data.csv")

x=dataset.iloc[:,[2,3]].values
x

y=dataset.iloc[:,4].values
y

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.25, random_state=0)

#feature scaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

print(x_train)
print(x_test)

#fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(x_train, y_train)

print(x_test)

y_pred=classifier.predict(x_test)
y_pred

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

y_pred = classifier.predict([[0.38358493,0.99784738]])
print(y_pred)
