# -*- coding: utf-8 -*-
"""Asita_Ganatra_DWM_PRACTICAL_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TqaHrBvwbcZRnF7IpPtIVNy6ZRHPDpQR
"""

import pandas as pd
import numpy as np
print('Hello')

#Cell 1
dataset = pd.read_excel('/content/Employee_Data.xls')

#Cell 2
dataset.isnull().sum()

dataset

x=dataset.iloc[:,3:6].values
x

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = 'NaN', strategy='median')
imputer = SimpleImputer().fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = 'NaN', strategy='most_frequent')
imputer = SimpleImputer().fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])
print(x)
